server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  profiles:
    include: devDB,devJpa
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


#监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"  #可以查看spring环境的所有端点
        exclude: "/health" #排除health端点
  endpoint:
    health:
      show-details: always

#日志配置
logging:
  level:
    com.geeko: debug
    org.springframework: warn
    com.atomikos: debug